tombatossals/angular-openlayers-directive

src/directives/marker.js
Update style for watch properties of markers.
=> Style for update properties markers

src/services/olMapDefaults.js
This should resolve https://github.com/tombatossals/angular-openlayers-directive/issues/47
Still missing an example though
=> Applying user defined styles to defaults

examples/103-controls-custom-example.html, src/directives/control.js, test/unit/controlsSpec.js
I attempted to do this in a similar way to layer.js by using a properties scope variable.
=> Added the ability to specify custom controls to olControl

src/directives/marker.js
Added listener for the 'touchend' event so it will handle showing the label if fired first.
=> Optimized marker clicking response for touch devices

examples/045-layers-geojson-example.html, examples/067-marker-custom-icon-example.html, src/services/olHelpers.js, test/unit/helplerSpec.js
custom icons are not visible since #77 is merged.
=> custom marker icons are not visible

README.md, src/services/olHelpers.js
hi,
just found a couple of `console.log` statements like "Hola" and so on in your code :smile: 
Removed them + was so cheeky to also link the contributions guidelines directly from the README.md as I was searching them prior to sending this PR.
Btw, seems like on the latest master one unit test fails. Gives me
```
PhantomJS 1.9.7 (Windows 7) Method: olHelpers.createStyle makes circle feature style FAILED
```
(you should include a travis badge on the README as well :wink: )
=> Remove console.log statements

src/services/olHelpers.js
=> Add possibility to set maxZoom for Bing maps

src/directives/marker.js
This PR fixes two issues experienced in some mobile browsers/ WebViews:
* The 'click' event is fired together with the 'touchend' event which causes the marker click/label handlers to be called twice.
* 'touchend' is being fired after the user has placed his finger on a marker, but intended to pan the map and not tap on a marker.
Both issues are solved by setting up a cooldown flag which helps filter our unneeded 'click' and 'touchend' events and prevents triggering of the handlers when they shouldn't be triggered.
=> Better handling of tap events on certain platforms

src/directives/marker.js
Fixes the marker removal in a non-empty marker array
=> Fix marker removal not removing a marker, see issue #110

src/directives/layer.js
@juristr 
adds check for the 'setStyle' method
=> adds check for the 'setStyle' method

src/directives/marker.js
resolves #193
Fix some issues caused by the addition of draggable markers.
Now dragging is also available for static image.
=> fix(marker): Improve draggable marker support for static image

src/directives/layer.js
Add processing of min and max resolution properties and set them after the layer is created.
This mimics the behavior of opacity, extent and visibility
=> feat(layer): set min and max resolution for the layer through properties

src/services/olHelpers.js
=> feat(olHelpers): add ability to use 'projection' and 'tileUrlFunction' options with XYZ sources

grunt/concat.js, package.json
=> feat: compatibility with commonjs

CHANGELOG.md
We don't have a changelog as it is being generated automatically
=> docs(CHANGELOG): Link to release GitHub release tab

src/directives/marker.js
Revised from #252  following orientations from @juristr
=> feat(marker): enable ng-click handling

src/services/olHelpers.js
Add 'style' attribute in wtms configuration
=> Add 'style' attribute in wtms configuration

doc/01-openlayers-directive.md
* Fix typo
* Fix links to existing files
* Remove link to inexistent file
=> docs(openlayers): Fix typo and links in doc/01-openlayers-directive.md

src/services/olHelpers.js
This PR addresses 2 vector / retina related issues with MapBox tiles 
1. Adds MapBox vector support via [OpenLayers MVT format](https://openlayers.org/en/latest/examples/mapbox-vector-tiles.html).
2. Updates MapBoxStudio to support 2x, which I noticed was available when looking at the Url on the MapBox studio editor page.
Closes #329.
Related to #334, although running `grunt` for this PR works fine, `grunt test:unit` fails locally due to issue #329.
=> feat:(olHelpers) Added support for Mapbox Vector Tiles

src/directives/control.js
Adds $watch on the olControl properties and in case updates the
corresponding control on the openlayers map.
=> feat(olControl): watch & reinitialize ctrls on map

src/services/olHelpers.js
This is the code enhancement for Issue #391.
=> feat(olHelpers.js): Support for Multiple Tile Server in XYZ Tile Layer
