src/directives/control.js, src/directives/marker.js, src/directives/path.js, src/services/olMapDefaults.js
This PR introduces the 'showOnMouseClick' property which can be set on the label attributes associated with the marker's properties.
I also re-indented the some of the code since the JSCS validator was failing without it.
=> Allow the user to configure markers to show their label on 'click' as an additional option rather than 'mouseover'

grunt/shell.js
Windows cannot interpret shebang ('#!/usr/bin/env node') in 'node_modules/protractor/bin/webdriver-manager'. Therefore on windows node must be explicitly called in order to run the tests.
=> Explicitly call node for shell commands

src/directives/openlayers.js
The current OpenLayers directive does not allow updates on the width and height attributes (data binding). As this is sometimes necessary, putting these attributes into the scope should be useful.
The updateSize() function of the OpenLayers Map class notifies the Viewport such that it can adapt.
Static values need to be wrapped in single quotation marks. An example:
<openlayers width="'100%'" height="customHeight"></openlayers>
=> Make width and height of the OpenLayers directive a dynamic scope attribute

src/directives/marker.js
This PR optimizes the usage of markers by limiting the number of vector layers used by markers on a single map instance to 1, instead of having one vector layer per marker.
It's doing that by keeping the reference to the layer designated for markers for each map and providing it when a marker is on created on a specific map.
This improves both rendering performance and helps avoid the openlayers maximum layer count (which is around 75).
=> Optimized marker layer management

src/directives/marker.js
This is an addition to https://github.com/tombatossals/angular-openlayers-directive/pull/64
It regains the possibility of listening to 'touchend' events on overlays.
(like tapping marker label's contents, in my use case)
=> Changed the touchend listener to be placed on the canvas directly

src/directives/layer.js
ol.layer.Base/Tile/etc. offer more functionality than the directive offers by now. Extent is one of the most important ones.
It should be either evaluated which fields are necessary es well or they could be added on demand.
=> The extent property of a ol.layer.Base component should be editable.

src/services/olHelpers.js
Supporting MapBox as a tile source for layers, which also switches to an alternative tile set that MapBox offers for high DPI screens if the screen pixel ratio is larger than 1. (gives the map a sharper look on mobile devices)
=> Support for MapBox as a tile source

src/directives/marker.js
This provides an alternative method for specifying the content for marker labels, by enabling 'transclude' on the marker directive and handing the label if the existing method is used or the new one.
By doing this, content bound to an angular scope can be placed in the label, so the label could handle user input.
=> Allows to transclude content for marker labels

src/directives/layer.js, src/services/olHelpers.js
If the user adds an index property to the `ol-layer-properties`, the code now tries to maintain that layer number. It only enforces the index when
1. the layer is added
2. the layer properties (or index) are modified
The changes require all code to use olHelpers code to access the `ol.Map.getLayers()` layer collection. If the indicated index is larger than the number of layers, `null` layers are inserted until the number of layers is correct. When inserting or removing a layer, all subsequent layers are shifted until a `null` value is encountered, so that layers after a `null` layer are not shifted.
The use of an index by the user is optional. Users can update the underlying array as follows:
JavaScript:
```
$scope.layers = [layer1, layer2]
$scope.updateLayerOrder = function() { …
```
=> Added index to layers and optionally to properties (fixes #72)

src/directives/center.js
I wonder ol.proj.transformExtent() should be used to transform an extent object.
=> The bounds is not correct

examples/045-layers-geojson-example.html, examples/058-layers-geojson-style-function.html, examples/json/LIS.geo.json, examples/json/features.json, src/services/olHelpers.js
Addresses issues #51 #74 #57.
The createLayer function is now recursive and parses style trees such as:
style:{
image:{
circle: {
radius: 5,
fill: {
color: 'red'
}
}
}
In addition, we can now handle the case where someone creates a tree that also contains an openlayers style constructor.  In the above, fill could instead be:
fill: new ol.layers.Fill({
color: 'red'
})
This way users of this directive will have access to any style features that may not be included in the tree parsing.
The last change is that we can have a function for the style.  The new example 058 shows an example.  There is some extraneous junk in the function that I should remove.
=> Circles and style functions

.gitignore, src/services/olHelpers.js
Hi,
we're developing a GIS application on the basis of Angular and OpenLayers and I just started to use your directive (which btw is supercool).
What I discovered, though, is that in the case of TileWMS services it is currently not possible to use the `urls` property.
```javascript
case 'TileWMS':
if (!source.url || !source.params) {
$log.error('[AngularJS - Openlayers] - TileWMS Layer needs valid url and params properties');
}
...
```
Instead, OpenLayers permits to have a confguration like this:
```javascript
new ol.layer.Tile({
title: "My title",
source: new ol.source.TileWMS({
urls: [
'http://url1/geoserver/wms',
'http://url2/geoserver/wms',
'http://url3/geoserver/wms',
],
params: {
LAYERS: 'SomeLayerName'
},
serverType: 'geoserver'
})
}),
```
This PR fixes the issue. Please have a …
=> Allow to specify the "urls" property in the case of TileWMS services

src/services/olHelpers.js
in other words, center cannot be set outside this extent.
In my case it was crucial so user cannot pan outside of the map.
Documented in http://openlayers.org/en/v3.3.0/apidoc/ol.View.html?unstable=true
=> Allow setting the extent that constrains the center

src/services/olHelpers.js
Relevant only to ol.source.ImageStatic source.
A function that takes an ol.Image for the image and a {string} for the src as arguments. It is supposed to make it so the underlying image ol.Image#getImage is assigned the content specified by the src. If not specified, the default is
```javascript
function(image, src) {
image.getImage().src = src;
}
```
Providing a custom imageLoadFunction can be useful to load images with post requests or - in general - through XHR requests, where the src of the image element would be set to a data URI when the content is loaded.
=> Optional function to load an image given a URL

src/services/olHelpers.js
This piece of code doesn't work any more in the latest version:
```javascript
olData.getMap().then(function(map) {
var layers = map.getLayers();
layers.forEach(function(layer) {
if (layer.get('name') === 'japan') {
var extent = layer.getSource().getExtent();
map.getView().fitExtent(extent, map.getSize());
}
})
});
```
The problem is that the layer name is no more set correctly as already mentioned in issue #92. This PR fixes it.
_Btw, one should add tests to make sure this doesn't happen again. I'd also be willing to add them, but the current tests on master don't pass and it would take me too long to figure out why._
=> Fix for setting of the layer name

src/directives/marker.js
Fixes https://github.com/tombatossals/angular-openlayers-directive/issues/76
This allows to define marker click (and tap) handlers in this manner:
```
// In the controller
$scope.marker = {
lat: 48.858093,
lon: 2.294694,
onClick: function (event, properties) {
console.log(this); // ol.Feature instance
console.log(properties); // === $scope.marker
}
}
```
```
<ol-marker ol-marker-properties="marker" ></ol-marker>
```
=> Marker option to handle click and tap events

src/services/olHelpers.js
Currently, if for some reason you don't specify the correct source type (i.e. Stamen, BingMaps etc...) you get this error on the console, which doesn't allow to immediately track down the real cause.
This PR adds a `$log.warn` indicating that no ol3 compatible source could be created out of the provided type. Thus you get something like this:
Personally this would have helped me find my issue much faster :smiley: 
@tombatossals What's your opinion on this?
=> Enhancement: $log.warn when no ol3 source could be created with the provided source type

src/directives/marker.js
Feature to show a marker's overlay until the user enters the mouse in other marker, when the overlay is changed to display the new marker's info. With this new behaviour an overlay is always visible unless the user clicks on a free marker zone of the map, which forces the visible overlay to close itself.
=> Support keepOneOverlayVisible feature in markers

src/services/olHelpers.js
This PR fixes some configuration issues with WMTS layers. Specifically it
- correctly maps the `layers` param
- adds support for the `urls` array (instead of just giving a single `url` property)
Thx for merging in @tombatossals
=> Fix configuration properties for WMTS layers

src/services/olHelpers.js
Text styles might contain a property 'text' which should be displayed directly.
```
{
"text":{
"text":"text text",
"offsetX":0,
"offsetY":0,
"scale":3,
"rotation":0,
"fill":{
"color":"rgba(255,128,0,1)"
},
"stroke":{
"color":"rgba(128,128,128,1)",
"width":1
}
}
}
```
Problem was that since 'text' is a style keyword, the previous implementation
looped into it, trying to convert the 'text text' string into an ol3 style
object.
=> fix(olHelpers): text styles might contain text strings

src/directives/openlayers.js, src/services/olHelpers.js
I could not find a way to alert on view events (ie; resolution changes).  This solution seemed to work well, and matches the syntax of the other events.
=> Allow map view events to be set like map and vector layer events

src/services/olHelpers.js
I came upon a case where I could get a TypeError error while checking against the layer name of the olLayer if the object was null (rapidly updating system).  
The current code could allow an openlayers.layers event to be dispatched when the feature was not part of the layer (since null will pass angular.isDefined() with a true value).  I updated the return value to undefined to prevent the event from being fired (please disregard this pull request if the current behavior is intentional).
=> Add null check to olLayer before checking its name (setVectorLayerEvents)

CONTRIBUTING.md
@tombatossals what do you think about this? We could apply them starting from v1.0 on and possibly also automate the changelog generation by using the semantic-release package. I mentioned it briefly in #155 .
Let me know what you think about this :smile:
=> Add commit message guidelines from Angular

src/services/olHelpers.js
fix for error with new versions of openlayers where .XYZ returns "not a function"
=> fix(olHelpers): change ol.tilegrid.XYZ to ol.tilegrid.createXYZ

src/services/olHelpers.js
This update allows custom attributes to be added to a layer when the layer
is defined.  For instance if a user wants to add a layer property 'selectable'
they can defined it as: customAttributes: { 'selectable': true }
=> feat(olHelpers): allow custom attributes to be added to a layer

doc/03-defaults-attribute.md
Updated docs to reflect the new attribute naming, from "defaults" to "ol-defaults". Also fixed the link to the example and the names of the "interactions" default.
=> docs: updated defaults attribute syntax & link to example

src/directives/layer.js
There was an error in the logic in version 1.3.0 of the
directive which caused Tile layers with TileWMS sources
to not render when the layer was updated.  Plunker which
demonstrates fix http://plnkr.co/edit/NI7GkRkhJvxXM8OxroMw?p=info
closes #213
=> fix(layer): change min/max resolution logic to fix #213

examples/105-controls-overviewmap-example.html, src/services/olHelpers.js
Added buildin ol3 overviewmap control to be available by name in olControl directive.
Using: `<ol-control name="overviewmap"> </ol-control>`
Also added relevant example.
=> feat(olHelpers): added builtin overviewmap control

src/services/olData.js, src/services/olHelpers.js
The function obtainEffectiveMapId was declared in the helper and only used in OlData. 
Moving it in OlData prevent future cyclic dependency and a better separation of concern.
Thanks
=> refactor(olData): move obtainEffectiveMapId function in olData instead using it from olHelpers, reducing dependency injection

src/services/olHelpers.js, test/unit/layersSpec.js
Ensure dataProjection is set when reading GeoJSON features to support projection conversion properly.
Fixes #232
=> fix(olHelper): multiple projection support for GeoJSON layers

src/directives/layer.js, src/services/olHelpers.js
Often it might be needed to be able to manipulate the ol3 layer that's
been handed to ol3 by angular-openlayers-directive. This allows for things like
```html
<openlayers>
<ol-layer ... on-layer-created="ctrl.onLayerCreated(oLayer)"></ol-layer>
</openlayers>
```
And on the controller/component:
```javascript
function MyController() {
var vm = this;
vm.onLayerCreated = function(oLayer) {
// oLayer is the original ol3 layer that's
// being registered
var source = olayer.get('source');
...
}
}
```
@ageblade @claustres @Pedrazl @nbiton Would you be willing to review this change? What do u think about such addition? Thoughts welcome :smiley:
=> feat: add onLayerCreated callback to manipulate original ol3 layer

src/directives/path.js
This allows to pass styling information to ol-path directive via the "ol-style" property. A constrained example:
```
/* js */
$scope.pathStyle = {
stroke: {
color: [0, 0, 255, 0.5],
width: 5,
}
};
/* html */
<ol-path ng-repeat="path in paths" coords="{{path.coord}}" ol-style="pathStyle"></ol-path>
```
=> feat(path): Support passing custom style.

src/services/olHelpers.js
The commit introduces a workaround to not recreate a WMS layer each time a parameter is updated in the source object (e.g. using updateParams). This allows a smooth layer reloading of WMS layers when a layer parameter is updated (e.g. when displaying timeseries data).
Example:
`source.updateParams({'TIME': newTime});`
Without the fix the line above forces a recreation of the layer.
=> fix(olHelpers): allow smooth layer reload when updating params of WMS layer

package.json, test/protractor.conf.js
End-to-end tests were failing to run after pulling down the latest version:
Error: No selenium server jar found at the specified location (...\angular-openlayers-directive\node_modules\protractor\selenium\selenium-server-standalone-2.45.0.jar). Check that the version number is up to date.
`protractor.conf.js` was looking for `selenium-server-standalone-2.45.0.jar`, whereas the version that got pulled down after running `npm install` and `grunt test:e2e` was 2.47.1.  They sometimes update the version of selenium-webdriver in minor version updates of protractor (for example, protractor 2.4.0 updated selenium webdriver to 2.47.0 - see the [protractor changelog](https://github.com/angular/protractor/blob/master/CHANGELOG.md)).
Since `protractor.conf.js` requires an exact version of selenium …
=> chore(build): fix protractor install

examples/030-custom-parameters-example.html, src/directives/openlayers.js, src/services/olMapDefaults.js
Fixes #261.
I also modified the custom parameters example (`030-custom-parameters-example.html`) to include these options. To see this change in action, browse to that example, try panning the map, and note that tiles are being fetched even while you're still dragging.
=> feat(defaults): add support for loadTilesWhileAnimating and loadTilesWhenInteracting options

package.json
In order to not have a global bower installed and allow dev to start working just after an `npm install`, I've added a postinstall script which execute bower install (from local env, not global).
=> chore(script): add an npm script to install bower dep after npm install

examples/055-layers-geojon-dynamic-load-example.html
In latest version, example 55 doesn't work because the projection was incorrectly set. This problem appears after the PR #233. The gh-page version isn't up-to-date with the lib version, so the problematic behavior can be seen only on dev env.
Linked to #259
=> fix(example): modification in example 55

src/services/olHelpers.js
added a custom set of imageExtent to imageStatic layers.
example:
```
/* js */
app.controller("StaticImageController", [ '$scope', function($scope) {
angular.extend($scope, {
center: {
coord: [ 900, 600 ],
zoom: 3
},
defaults: {
view: {
projection: 'pixel',
extent: [ 0, 0, 1800, 1200 ]
}
},
static: {
source: {
type: "ImageStatic",
url: "http://blog.wallpops.com/wp-content/upLoads/2013/05/WPE0624.jpg",
imageSize: [ 1800, 1200 ]
},
zIndex: 1
},
eiffel: {
source: {
type: "ImageStatic",
url: "images/eiffel.jpg",
imageSize: [ 120, 180 ],
imageExtent: [830, 650, 880, 730]
},
opacity: 0.75,
zIndex: 2
}
});
} ]);
/* html */
<openlayers ol-center="center" ol-defaults="defaults" custom-layers="true" height="600px">
<ol-layer ol-layer-properties="static"></ol-layer>
<ol-layer …
```
=> feat(olHelpers): custom imageExtent support for ImageStatic layers

package.json
This post-install execution leads environnement depending of the library to have the post-install hook triggered, even if it's only a dependency.
Linked to #282
=> fix(package.json): remove the post build install of bower

src/services/olHelpers.js
ESRI layer `World_Light_Gray_Base` mentioned in example `112-layers-esri-basemaps-example.html` requires a different `_urlBase` than the other ESRI layers. The same applies to the layer `World_Dark_Gray_Base`.
Linked to #134
=> fix(olHelpers): fix url for ESRI basemaps World_Light_Gray_Base and World_Dark_Gray_Base

src/services/olHelpers.js
`extractStyles` is a parameter for `ol.format.KML`, and not `ol.source.Vector`. This fixes also the bug described in #268.
Linked to #268
=> fix(olHelpers): pass extractStyles to ol.format.KML

src/directives/marker.js
Adding and removing markers leads to retention leak. Unregistering handlers on destroy
=> Handlers need to be unregistered to avoid memory retention leaks

package.json
Openlayers 3.8.x breaks npm install because of a specific version of a dependency to jsdoc. By updating we avoid this dependency.
This fixed issue #311
=> fix(package.json): update the openlayers version

src/directives/marker.js, test/unit/markerSpec.js
On a $scope.$destroy the unregisterHandler function is called. This function removes all the eventListeners.
The properties object that these listeners are attached to, might not exist. So during the teardown, an error will be raised.
This fixes issue #314
=> fix(marker.js): add check to scope teardown

src/services/olHelpers.js
Adding support for TileArcGISRest makes it easy to consume a wide variety of ArcGIS MapServer endpoints provided by Esri (beyond those allowed by the EsriBaseMaps type). This also makes it easy to reference custom MapServer endpoints that may be hosted on private servers.
Killed previous PR#316 so I could put this under a feature branch.
=> feat (olHelpers.js): add layer support for TileArcGISRest source type

src/services/olHelpers.js
Fixes/implements #273. 
This enables the use of custom `tileLoadFunction` or `imageLoadFunction`, which is required, for instance, to display cross-origin authenticated layers, as in https://github.com/openlayers/ol3/issues/5401#issuecomment-222135186
=> Add support for tileLoadFunction and imageLoadFunction

src/services/olHelpers.js
Allows the wrapX property to be passed into the source. It has only been applied to sources that accept this property based on the OL3 docs. The pass-through property defaults to true, as it is in OL3.
This PR is very similar to #198. The exceptions being lack of ternary operator and only applying the property to sources that have support for it (to avoid confusion and properly match the OL3 docs). Sorry for the repeat PR. But, seeing that #198 was almost a year old and is listed as having merge conflicts... I just chose the simpler path forward.
=> Add wrapX support

src/services/olHelpers.js
This addresses issue #337. It is a one-character change, changing the protocol from http to https.
=> fix(olHelpers.js): use HTTPS Mapbox URL

src/services/olHelpers.js
This change tries to infer the attribution given the source configuration of the ol3 object. Apparently each OL3 source type might have different properties for storing the attribution. Thus the code needs to iterate over them and "search" for the presence of it.
WARNING: This also slightly changes the default behavior, meaning while currently the attribution had to be enabled explicitly you now have to opt-out by setting the `source.attribution = false`.
=> feat(olHelper): auto-detection of attribution

src/directives/openlayers.js
Set map object to null when controller is destroyed. Was causing memory leaks, Fix for #393
=> fix(openlayers.js): Memory leak issue
